version: "3"

services:
  app:
    build: .
    container_name: nutech-ppob-api
    restart: always
    ports:
      - "3005:3005"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
    environment:
      - PORT=3005
      - DB_HOST=db
      - DB_USER=nutech_user
      - DB_PASSWORD=nutech_password
      - DB_NAME=nutech_ppob
      - JWT_SECRET=nutech_secret_key
      - JWT_EXPIRES_IN=12h

  db:
    image: mysql:8.0
    container_name: nutech-ppob-db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=nutech_ppob
      - MYSQL_USER=nutech_user
      - MYSQL_PASSWORD=nutech_password

volumes:
  mysql_data:
